name: Action di Anog
on:
    push:
jobs:
    training:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    tag

            - uses: actions/setup-python@v5
              with:
                python-version: '3.12.7'
            - run: |
                python -m pip install --upgrade pip
              working-directory: tag
            - run: |
                pip install -r requirements.txt
              working-directory: tag
            - run: |
                python modello.py
              working-directory: tag
            - run: ls -la tag/

            - uses: actions/upload-artifact@v4
              with:
                name: modello-ml
                path: anog/modello_regressione.joblib